# Generated by Django 4.2 on 2023-05-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_supervisor_agent_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='supervisor',
            new_name='team',
        ),
    ]
