# Generated by Django 4.2 on 2023-06-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delete_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='converted',
        ),
    ]
