# Generated by Django 4.2 on 2023-06-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('orders', '0003_rename_service_details_order_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
